# Generated by Django 3.2.10 on 2022-08-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
